name: Hugo Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout docs content
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.7.1
        with:
          fetch-depth: 0 # This is required for hugo Lastmod to function properly

        ### Hugo builds

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 'latest'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: |
          make build-example-site
