name: Build Hugo Docs with PR Theme

on:
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    name: Build Hugo Docs with PR Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hugo theme
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0 # This is required for hugo Lastmod to function properly

      - name: Clone documentation repo
        run: |
          git clone https://github.com/nginx/documentation.git docs

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.27.1"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Build Hugo site
        working-directory: docs
        run: |
          hugo --gc -e production --baseURL="https://frontdoor-test-docs.nginx.com/nginx-hugo-theme/${{github.event.pull_request.number}}"
