name: Slack notification for new theme release

on:
  repository_dispatch:
    types: [trigger-slack-notification]

permissions:
  contents: read

jobs:
    release-notification:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          actions: read # for 8398a7/action-slack
          checks: read
        steps:
          - name: Send notification
            uses:  8398a7/action-slack@1750b5085f3ec60384090fb7c52965ef822e869e # v3.18.0
            with:
                status: custom
                custom_payload: |
                  {
                      username: 'Github',
                      mention: 'channel',
                      attachments: [{
                        title: `New theme release - ${{ github.event.client_payload.release_name }}`,
                        color: '#009223',
                        fields: [
                        {
                          title: 'Tag',
                          value: ${{ github.event.client_payload.tag_name }},
                          short: true
                        },
                        {
                          title: 'Author',
                          value: ${{ github.event.client_payload.author }},
                          short: true
                        },
                        {
                          title: 'Preview URL',
                          value: ${{ github.event.client_payload.previewURL }},
                          short: true
                        }]
                      }]
                  }
            env:
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
